# Generated by Django 2.1.2 on 2018-12-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181107_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='area',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='party_number',
        ),
        migrations.AddField(
            model_name='candidate',
            name='urls',
            field=models.CharField(default='www', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='username',
            field=models.CharField(default='user', max_length=15),
            preserve_default=False,
        ),
    ]
