# Generated by Django 2.1.2 on 2018-12-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20181204_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('urls', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
