# Generated by Django 2.1.2 on 2018-12-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20181204_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='urls',
            field=models.CharField(max_length=1000),
        ),
    ]
