# Generated by Django 2.1.2 on 2018-12-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20181204_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='btid',
            field=models.CharField(default='loginbutton', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpage',
            name='idid',
            field=models.CharField(default='username', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpage',
            name='pwid',
            field=models.CharField(default='password', max_length=40),
            preserve_default=False,
        ),
    ]
