# Generated by Django 2.1.2 on 2018-12-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20181209_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='intro',
            field=models.CharField(default='소개', max_length=100),
            preserve_default=False,
        ),
    ]
