# Generated by Django 2.1.2 on 2018-12-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='owner',
            field=models.CharField(default='ownerid', max_length=30),
            preserve_default=False,
        ),
    ]
